services:

  fedired-backend:
    build: .
    image: fedired-backend:develop
    container_name: fedired-backend
    hostname: fedired-backend
    restart: always
    depends_on:
      - redis
      - postgres
    expose:
      - 3000
    volumes:
      - ./files:/fedired/files
      - ./default.yml:/.config/default.yml:ro
    networks:
      fedirednet:

  redis:
    image: redis
    container_name: redis-fedired
    hostname: redis-fedired
    restart: always
    volumes:
      - ./redis:/data
    expose:
      - 6379
    networks:
      fedirednet:

  postgres:
    image: postgres:9.6
    container_name: postgres-fedired
    hostname: postgres-fedired
    restart: always
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./pg_backups:/pg_backups
    environment:
      - POSTGRES_USER=fedired
      - POSTGRES_PASSWORD=fedired
      - POSTGRES_DB=fedired
    expose:
      - 5432
    networks:
      fedirednet:

networks:
  fedirednet:
